---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  labels:
    run: {{ .Values.service.label }} 
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}  
    targetPort: {{ .Values.service.internalPort }}
    nodePort: {{ .Values.service.nodeport }}
    protocol: TCP
    name: http
  selector:
    run: {{ .Values.service.selector }}
