Use this api By passing namespace to get pods information
    ---
    tags:
      - list_namespaced_pod API
    parameters:
      - name: namespace
        in: path
        type: string
        required: true
        description: The namespace name you want its pods info
    responses:
      500:
        description: Error The namespace is not valid!
      200:
        description: namespace is valid!
        schema:
          id: namespace_name
          properties:
            namespace:
              type: string
              description: The namespace name
              default: default
