---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-client-python-deployment
spec:
  selector:
    matchLabels:
      run: k8s-client-python-deployment-pods
  replicas: 2
  template:
    metadata:
      labels:
        run: k8s-client-python-deployment-pods
    spec:
      volumes:
      - name: html
        persistentVolumeClaim:
           claimName: html-claim
      containers:
      - name: k8s-client-python-container
        image: k8s-client-python
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: html
          mountPath: /html
        command: ["/bin/sh", "-c"]
        args:
          - ./script/entry.sh;
            while true; do
              date >> /html/index.html;
              python ./app/get_pod_info_table_view.py > /html/index.html;
              sleep 22;
            done
