---
apiVersion: v1
kind: Service
metadata:
  labels:
  k8s-app: k8s-client-python
  name: k8s-client-python
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5035
  selector:
  k8s-app: k8s-client-python
